### PR TITLE
autogenerate short urls

### PR DESCRIPTION
**Pull request by ryanwinchester**
How about this then?

I merged @dshoreman's branch into here, btw, since I needed the migration.

With this, if you create without defining `short_url` specifically, it will be autogenerated (and retry generating until we get no unique errors).

However, you will still get an error if you try to use a specific a `short_url` and it is not unique.

### CODE REVIEW

**Comment by mikerogne** [comment]
Seems to be a lot going on here, not sure what to make of all of it.

I don't like the change to phpunit.xml for sure, not necessary. And there are conflicts.

**Comment by ryanwinchester** [comment]
> Seems to be a lot going on here, not sure what to make of all of it.

I added like two methods. There is a comment description for the more complicated bit that actually does the autogenerating 🤐.

> I don't like the change to phpunit.xml for sure, not necessary. And there are conflicts.

That just allows you to define the testing DB configuration with your `.env` variables, but defaults to the sqlite version.

**Comment by mikerogne** [comment]
>I added like two methods. There is a comment description for the more complicated bit that actually does the autogenerating 🤐.

Probably right, but going through all of the PR's at once became a little overwhelming. Not used to being on this side of the equation. At any rate, I would prefer to follow Laravel convention & instead of overwriting `create()`, just listening for the appropriate event & handling it there if we went that route.

> That just allows you to define the testing DB configuration with your .env variables, but defaults to the sqlite version.

I already had created a new connection & updated the phpunit.xml to use it. Your code basically duplicated it w/ no benefit?

**Comment by ryanwinchester** [comment]
> Probably right, but going through all of the PR's at once became a little overwhelming. Not used to being on this side of the equation. At any rate, I would prefer to follow Laravel convention & instead of overwriting create(), just listening for the appropriate event & handling it there if we went that route.

I thought about adding an observer, but seemed like overkill for a 1-model app.

> I already had created a new connection & updated the phpunit.xml to use it. Your code basically duplicated it w/ no benefit?

From what I saw you could not change the test db with your `.env` file, but with my changes, you could.

**Pull request closed without merging**
